title: "mus street photography"
author:  "mus_photography"
baseurl: "" 
url: "https://m5553.github.io"
author: mus

collections:
  books:
    output: true
    permalink: /books/:path/
  blog:
    output: true
    permalink: /blog/:path/

markdown: kramdown

theme: